# Generated by Django 4.2.4 on 2023-08-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
